<?php
declare(strict_types=1);

namespace CakeMongo\Database;

use Cake\Database\Connection as CakeConnection;
use CakeMongo\Database\Driver\Mongodb;

class Connection extends CakeConnection
{
    /**
     * @inheritDoc
     */
    protected function createDrivers(array $config): array
    {
        $config['driver'] = Mongodb::class;

        return parent::createDrivers($config); // TODO: Change the autogenerated stub
    }

    /**
     * Mongo doesn't support transactions
     *
     * @param callable $callback Transaction callback
     * @return false
     * @noinspection PhpMissingParentCallCommonInspection
     */
    public function transactional(callable $callback)
    {
        return false;
    }

    /**
     * Mongo doesn't support foreign keys.
     *
     * @param callable $callback Transaction callback
     * @return false
     * @noinspection PhpMissingParentCallCommonInspection
     */
    public function disableConstraints(callable $callback)
    {
        return false;
    }
}
