<?php
declare(strict_types=1);

namespace CakeMongo\ODM;

use Cake\ORM\Table;

/**
 * MongoDB collection represented as Table.
 */
class Collection extends Table
{
    /**
     * @param string $type
     * @param array $options
     * @return \Cake\ORM\Query
     */
    public function find(string $type = 'all', array $options = []): \Cake\ORM\Query
    {
        $query = Query();
        return $this->callFinder($type, $query, $options);
        return parent::find($type, $options); // TODO: Change the autogenerated stub
    }
}
